version: "3.8"

services:
  website:
    restart: always
    build:
      context: ./website/
    env_file:
      - ./website/website.env
    ports:
      - "3000:3000"
    depends_on:
      - cms

  cms:
    restart: always
    build:
      context: ./cms/
    env_file:
      - ./cms/cms.env
    volumes:
      - ./cms/media/:/usr/src/portfolio/cms/media/
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  mongo:
    restart: always
    image: mongo:latest
    volumes:
      - ./mongo/data/db:/data/db/
    env_file:
      - ./mongo/mongo.env
