version: "3.8"

services:
  website:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports:
      - "3010:3000"

  cms:
    build:
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    ports:
      - "3011:3001"
